name: Serverless Prod Deployment

on:
  push:
    branches:
      - "main"
      - "master"

# Global concurrency control for GitHub Actions
concurrency:
  group: ${{ github.ref }}/deploy
  cancel-in-progress: true

env:
  DAGSTER_CLOUD_URL: "http://weatherdec2025.dagster.cloud"
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
  ENABLE_FAST_DEPLOYS: 'true'
  PYTHON_VERSION: '3.10'
  DAGSTER_CLOUD_FILE: 'dagster_cloud.yaml'

# GitHub Actions workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagster dagster-cloud
          
      - name: Create dagster_cloud.yaml
        run: |
          cat > ${{ env.DAGSTER_CLOUD_FILE }} << 'EOL'
          # Dagster Cloud deployment configuration
          # This file is generated by the GitHub Actions workflow
          # See: https://docs.dagster.io/dagster-cloud/developing-testing/deployment-settings
          
          concurrency:
            pools:
              granularity: 'run'  # 'op' or 'run'
              default_limit: 1
              op_granularity_run_buffer: 1
            
            runs:
              max_concurrent_runs: 10  # 1-50 for Serverless
              tag_concurrency_limits:
                - key: 'resource'
                  value: 'high_memory'
                  limit: 2
          
          run_monitoring:
            start_timeout_seconds: 1200     # 20 minutes
            cancel_timeout_seconds: 600     # 10 minutes
            max_runtime_seconds: 14400      # 4 hours
          
          run_retries:
            max_retries: 3
            retry_on_asset_or_op_failure: false
          
          sso_default_role: EDITOR  # NO_ACCESS, VIEWER, LAUNCHER, JOB_VIEWER, JOB_EDITOR, EDITOR, ADMIN
          
          non_isolated_runs:
            enabled: true
            max_concurrent_non_isolated_runs: 2
          EOL
          
          echo "Generated ${{ env.DAGSTER_CLOUD_FILE }} with deployment settings"
          cat ${{ env.DAGSTER_CLOUD_FILE }}
      
      - name: Login to Dagster Cloud
        uses: dagster-io/dagster-cloud-action@v3
        with:
          organization_id: ${{ vars.ORGANIZATION_ID }}
          api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}

      - name: Deploy to Dagster Cloud
        env:
          DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
        run: |
          dagster-cloud serverless deploy \
            --url ${{ env.DAGSTER_CLOUD_URL }} \
            --deployment weather-prod \
            --working-directory . \
            --python-version ${{ env.PYTHON_VERSION }}
            
      - name: Verify deployment
        run: |
          echo "Deployment to ${{ env.DAGSTER_CLOUD_URL }} completed successfully"
